service: jsxmail-cloud-api

useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-monorepo
  - serverless-domain-manager

package:
  patterns:
    - '.jsxmail/**'
    - 'node_modules/.prisma/client/**'
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

custom:
  serverless-offline:
    useChildProcesses: true
    reloadHandler: true
    httpPort: 3331
  customDomain:
    domainName: api.jsxmail.org
    basePath: ''
    stage: ${opt:stage, self:provider.stage, "dev"}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'