service: jsxmail-cloud-api

useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-monorepo

custom:
  serverless-offline:
    useChildProcesses: true
    reloadHandler: true
    httpPort: 3331

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  httpApi:
    cors: true
    disableDefaultEndpoint: true
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
  iam:
    role:
      statements:
        - Effect: Allow
          Action: '*'
          Resource: '*'

functions:
  main:
    handler: dist/main.handler
    events:
      - httpApi:
          method: '*'
          path: '*'