service: jsxmail

useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-monorepo

custom:
  serverless-offline:
    useChildProcesses: true
    reloadHandler: true
    httpPort: 3331

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 900
  httpApi:
    cors: true
    disableDefaultEndpoint: true
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
  iam:
    role:
      statements:
        - Effect: Allow
          Action: '*'
          Resource: '*'

functions:
  api:
    handler: dist/api.handler
    timeout: 30
    events:
      - httpApi:
          method: '*'
          path: '*'
  charge:
    handler: dist/workers/charge.handler
    events:
      - schedule: cron(50 23 * * ? *)
  storage-size:
    handler: dist/workers/storage-size.handler
    events:
      - schedule: cron(50 23 * * ? *)
  add-free-balance:
    handler: dist/workers/add-free-balance.handler
    events:
      - schedule: cron(50 23 * * ? *)