service: jsxmail-cloud-api

useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-monorepo
  - serverless-domain-manager

custom:
  serverless-offline:
    useChildProcesses: true
    reloadHandler: true
    httpPort: 3331
  customDomain:
    domainName: api.jsxmail.org
    basePath: ''
    stage: ${opt:stage, self:provider.stage, "dev"}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true