name: Deploy API
on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:

jobs:
  BuildAndDeploy:
    runs-on: self-hosted
    env:
      ENV_FILE: ${{ secrets.ENV_FILE }}
    steps:
      - uses: actions/checkout@v2
      - name: build image
        run: |
          cd apps/api
          echo "$ENV_FILE" > .env
          docker build . -t jsxmail-api
          docker rm -f jsxmail-api || true
          docker run -d --name jsxmail-api -p 3331:3331 jsxmail-api
