name: Deploy API
on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: build image
        run: docker build . -t jsxmail-api

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: delete container if exists
        run: docker rm -f jsxmail-api || true
      - name: run container
        run: docker run -d --name jsxmail-api -p 3331:3331 jsxmail-api
