name: Deploy API
on:
  push:
    branches:
      - main
      - cloud
    paths: 
      - 'api/**'
  workflow_dispatch:
      
jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Go to api directory
        run: |
          cd api
          pwd
      - name: install yarn
        run: npm install -g yarn
      - name: Create environment file
        run: echo ${{ secrets.ENV }} > .env
      - name: Configure AWS credentials
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}
      - name: install dependencies
        run: yarn
      - name: Prepare everything
        run: yarn prepare:all
      - name: Deploy API
        run: yarn deploy:aws