name: Deploy API
on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:

jobs:
  DeployAPI:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: app-pages
      - name: install pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: false
      - name: Install fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Prepare and Deploy API
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          cp -rf app-pages/apps/api/. ./api
          cd api
          echo "$ENV_FILE" > .env
          pnpm install
          pnpm run prepare:all
          pnpm run build
          flyctl deploy --remote-only \
          --build-secret AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
          --build-secret AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
          --build-secret AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
