name: Deploy API
on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:

jobs:
  DeployAPI:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install bun
        uses: oven-sh/setup-bun@v1
      - name: Install fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Prepare and Deploy API
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          cd packages/database
          echo "$ENV_FILE" > .env
          cd ../../
          cd apps/api
          echo "$ENV_FILE" > .env
          bun install
          bun run build
          cp -rf ../../node_modules ./
          rm -rf ./node_modules/@jsx-mail/database
          cp -rf ../../packages/database ./node_modules/@jsx-mail
          flyctl deploy --remote-only \
          --build-secret AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
          --build-secret AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
          --build-secret AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
